### ISSUE TITLE
Docs for intelisense not working

### ISSUE THREAD

**Issue by tarithj** [GreenXenith/minetest-tools#43]
Hovering over functions dosen't show the doc entry for it
![image](https://github.com/GreenXenith/minetest-tools/assets/29999281/6c3a6225-744b-4da6-96b5-77a70f480c8c)

**Comment by GreenXenith** [comment]
It looks like you just have your doc menu disabled. `ctrl+space` should toggle that.

**Comment by GreenXenith** [comment]
This isn't a bug, the extension only provides autocomplete, not full intellisense. Once it is integrated with a language server it will have the behavior you are looking for.

**Comment by tarithj** [comment]
got it sorry for the confusion
