### ISSUE TITLE
Syntax Highlighting: Highlight the 'and' and 'not' operators

### ISSUE THREAD

**Issue by Skivling** [GreenXenith/minetest-tools#46]
In if statements, both the `and` and the `not` operators are currently white. This confuses me and made me double check the Lua documentation to make sure I was using the right operators, and that is wasn't supposed to be something like `&&` for and.

They should be purple, like `if`, `else`, & `end` are.

**Comment by GreenXenith** [comment]
Lua syntax highlighting is the job of editor themes and other extensions. Please try installing other themes and make sure your editor is recognizing your files properly as Lua.
