### ISSUE TITLE
Removed from marketplace?

### ISSUE THREAD

**Issue by FreeLikeGNU** [GreenXenith/minetest-tools#8]
This tool no longer seems available via install method or marketplace.

**Comment by GreenXenith** [comment]
User was using VSCodium which utilizes a different [extension marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace). Closing as there are no plans to maintain a copy on said marketplace (and there are ways to use the Microsoft Marketplace in VSCodium).
